@startuml

forums : forum_id [INTEGER]
forums : user_id [INTEGER]
forums : slug [CITEXT]
forums : title [TEXT]
forums --> users : user_id <--> nickname

posts : post_id [INTEGER]
posts : user_id [INTEGER]
posts : thread_id [INTEGER]
posts : forum_id [INTEGER]
posts : created [DATETIME]
posts : isEdited [BOOLEAN]
posts : message [TEXT]
posts : parent_id [INTEGER]
posts --> users : user_id <--> user_id
posts --> threads : thread_id <--> thread_id
posts --> forums : forum_id <--> forum_id
posts --> posts : parent_id <--> post_id

threads : thread_id [INTEGER]
threads : forum_id [INTEGER]
threads : user_id [INTEGER]
threads : created [DATETIME]
threads : message [TEXT]
threads : slug [CITEXT]
threads : title [TEXT]
threads --> forums : forum_id <--> forum_id
threads --> users : user_id <--> user_id

users : user_id [INTEGER]
users : nickname [CITEXT]
users : about [TEXT]
users : email [CITEXT]
users : fullname [TEXT]

votes : vote_id [INTEGER]
votes : user_id [INTEGER]
votes : voice [SMALLINT]
votes : thread_id [INTEGER]
votes --> users : user_id <--> user_id
votes --> threads : thread_id <--> thread_id

@enduml